<?php
//Bring in the methods implemneting node hooks. 
require 'CPSmodule.node.php'; 
/**
 * Implements hook_menu().
 * We add custom pages for adding and listing charges and payments to
 * properties. The routes are set here and the code for building
 * forms and pages is loaded from CPSmodule.pages.php. We use the .php extension
 * and not the conventional .inc as a security precaution, .inc not parsed
 * as php files and so can exposed the the browser if you know the direct url.
 * http://stackoverflow.com/questions/7129842/what-is-inc-and-why-to-use-it
 */
function CPSmodule_menu() {

  $items['payment_by_code'] = array(
    'title' => 'Add new payment',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('add_payment_by_code_form'),
    'access callback' => 'user_access',
    'access arguments' => array('Add Payment'),
    'file' => 'CPSmodule.pages.php', //Load the file with the page code. 
    'type' => MENU_NORMAL_ITEM,
  );
  $items['list_payments_by_prop'] = array(
    'title' => 'List payments by property',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('list_payments_by_prop_form'),
    'access callback' => 'user_access',
    'access arguments' => array('List Payment by Prop'),
    'file' => 'CPSmodule.pages.php',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['list_charges_by_prop'] = array(
    'title' => 'List charges by property',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('list_charges_by_prop_form'),
    'access callback' => 'user_access',
    'access arguments' => array('List Charge by Prop'),
    'file' => 'CPSmodule.pages.php',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['account_summary_by_code'] = array(
    'title' => 'View property account',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('account_summary_by_code_form'),
    'access callback' => 'user_access',
    'access arguments' => array('Prop Account'),
    'file' => 'CPSmodule.pages.php',
    'type' =>  MENU_NORMAL_ITEM,
  );
  $items['property_account_summary'] = array(
    'title' => 'Property account summary',
    'page callback' => 'CPSmodule_property_account_summary_view',
    'page arguments' => array(1,2,3),
    'access callback' => 'user_access',
    'access arguments' => array('Prop Acc Summary'),
    'file' => 'CPSmodule.pages.php',
    'type' => MENU_VISIBLE_IN_BREADCRUMB,
  );
  
  return $items;
}

/**
* Implementation of hook_permission()
* Allow access to our pages solely to autheticated users. These need to be set
* in the roles admin menu. 
*/
function CPSmodule_permission() {
  //dpm('CPSmodule_permission');
  return array(
    'Add Payment' => array(
      'title' => t('Add a payment'),
      'description' => t('Allow users to add a payment'),
    ),
    'List Payment by Prop' => array(
      'title' => t('List payments by prop'),
      'description' => t('Allow users to list payments by entering property code'),
    ),
    'List Charge by Prop' => array(
      'title' => t('List charges by prop'),
      'description' => t('Allow users to list charges by entering property code'),
    ),
    'Prop Account' => array(
      'title' => t('Account summary by prop'),
      'description' => t('Allow users to select an account summary by entering the property code and dates'),
    ),
    'Prop Acc Summary' => array(
      'title' => t('Account summary view page'),
      'description' => t('Allow users to see an account summary as selected'),
    )
  );
}

?>